### ISSUE TITLE
AttributeError: 'Football' object has no attribute 'grid'

### ISSUE THREAD

**Issue by Rinstein** [jidiai/Competition_Football#1]
File "D:/RL/Football/Competition_Football/run_log.py", line 92, in render_game
    screen = pygame.display.set_mode(g.grid.size)
AttributeError: 'Football' object has no attribute 'grid'

请问这个环境可以开着GUI跑吗？我设置了run_log中的render_mode和render_in_time为True，就报错了，应该怎么设置

**Comment by smoothsmooth** [comment]
可以的~render_mode设为True，render_in_time设为False，试一下~

**Comment by smoothsmooth** [comment]
可以的。render_mode设为True，render_in_time设为False，试一下~

**Comment by Rinstein** [comment]
这样设置可以跑，但是界面会无响应的，
![image](https://user-images.githubusercontent.com/30389856/163664414-0fa4f807-4fda-451b-babb-f0bc6e36f7da.png)

**Comment by smoothsmooth** [comment]
系统是Windows吧？试一下用Ubuntu的虚拟机。

**Comment by Rinstein** [comment]
好的，我这个是windows，python3.7的环境
