### ISSUE TITLE
Dependencies during the competition.

### ISSUE THREAD

**Issue by ghost** [jidiai/Competition_Football#2]
Hi, this project requires a specific version of Python and torch according to the README. Wondering if it is possible to use other dependencies for the submitted agent during the competition (Say, Python 3.7 and tf 1.x) ?

**Comment by smoothsmooth** [comment]
We are likely to accept Python 3.7, but the tensorflow version is 2.8.0 on the platform.
Maybe can try:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
when using tf.
The best way to test whether a specific dependency can be used is to submit the algorithm through the competition page.

**Comment by ghost** [comment]
Thanks for the reply. I see, will try it out by submit-and-test. 

Just another quick question: we're actually going to use our own proprietary lib which requires Python 3.7 and tf 1.x. 
Would appreciate if you could provide some examples on how to do that (e.g., how to install one's own dependencies on the submission)

Actually,
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
does not work in our case, as much of our stable code uses the `tf.contrib` stuff which is unavailable in `tensorflow.compat.v1`.

Also, will you consider other mechanism for supporting any dependencies? E.g., call each submission from a separate process and require the submission bind to a Python `virtualenv` where any Python version and private dependencies can be used.
